// apps/web/src/routes/login/+page.svelte
<script lang="ts">
  import { goto } from '$app/navigation'
  import { page } from '$app/stores'
  import {
    signInWithPopup,
    signInWithEmailAndPassword,
    signOut,
    getIdToken,
  } from 'firebase/auth'
  import { clientAuth, googleProvider } from '$lib/firebase'
  import { api } from '$lib/api'

  let email = $state('')
  let password = $state('')
  let error = $state<string | null>(null)
  let loading = $state(false)

  const redirectTo = $derived($page.url.searchParams.get('redirect') ?? '/')

  async function exchangeToken(idToken: string) {
    const { error: err } = await api.api.auth.session.post({ idToken })
    if (err) throw new Error((err.value as { message?: string })?.message ?? 'Login failed')
    await goto(redirectTo)
  }

  async function handleGoogle() {
    error = null
    loading = true
    try {
      const cred = await signInWithPopup(clientAuth, googleProvider)
      const idToken = await getIdToken(cred.user)
      await exchangeToken(idToken)
    } catch (e) {
      await signOut(clientAuth).catch(() => {})
      error = e instanceof Error ? e.message : 'Google sign-in failed'
    } finally {
      loading = false
    }
  }

  async function handleEmail(e: SubmitEvent) {
    e.preventDefault()
    error = null
    loading = true
    try {
      const cred = await signInWithEmailAndPassword(clientAuth, email, password)
      const idToken = await getIdToken(cred.user)
      await exchangeToken(idToken)
    } catch (e) {
      error = e instanceof Error ? e.message : 'Sign-in failed'
    } finally {
      loading = false
    }
  }
</script>

<div class="flex min-h-full items-center justify-center px-4">
  <div class="w-full max-w-sm space-y-8">
    <div class="text-center">
      <h1 class="text-2xl font-semibold tracking-tight">COMS Portal</h1>
      <p class="mt-1 text-sm text-neutral-400">Sign in to continue</p>
    </div>

    <button
      onclick={handleGoogle}
      disabled={loading}
      class="flex w-full items-center justify-center gap-3 rounded-lg border border-neutral-700 bg-neutral-900 px-4 py-2.5 text-sm font-medium hover:bg-neutral-800 disabled:opacity-50"
    >
      <svg class="h-5 w-5" viewBox="0 0 24 24">
        <path fill="#4285F4" d="M22.56 12.25c0-.78-.07-1.53-.2-2.25H12v4.26h5.92a5.06 5.06 0 0 1-2.2 3.32v2.77h3.57c2.08-1.92 3.28-4.74 3.28-8.1z"/>
        <path fill="#34A853" d="M12 23c2.97 0 5.46-.98 7.28-2.66l-3.57-2.77c-.98.66-2.23 1.06-3.71 1.06-2.86 0-5.29-1.93-6.16-4.53H2.18v2.84C3.99 20.53 7.7 23 12 23z"/>
        <path fill="#FBBC05" d="M5.84 14.09c-.22-.66-.35-1.36-.35-2.09s.13-1.43.35-2.09V7.07H2.18C1.43 8.55 1 10.22 1 12s.43 3.45 1.18 4.93l2.85-2.22.81-.62z"/>
        <path fill="#EA4335" d="M12 5.38c1.62 0 3.06.56 4.21 1.64l3.15-3.15C17.45 2.09 14.97 1 12 1 7.7 1 3.99 3.47 2.18 7.07l3.66 2.84c.87-2.6 3.3-4.53 6.16-4.53z"/>
      </svg>
      Continue with Google
    </button>

    <div class="relative">
      <div class="absolute inset-0 flex items-center">
        <div class="w-full border-t border-neutral-800"></div>
      </div>
      <div class="relative flex justify-center text-xs text-neutral-500">
        <span class="bg-neutral-950 px-2">or</span>
      </div>
    </div>

    <form onsubmit={handleEmail} class="space-y-4">
      <div>
        <label class="mb-1 block text-xs text-neutral-400">Email</label>
        <input
          type="email"
          bind:value={email}
          required
          class="w-full rounded-lg border border-neutral-700 bg-neutral-900 px-3 py-2 text-sm focus:border-indigo-500 focus:outline-none"
        />
      </div>
      <div>
        <label class="mb-1 block text-xs text-neutral-400">Password</label>
        <input
          type="password"
          bind:value={password}
          required
          class="w-full rounded-lg border border-neutral-700 bg-neutral-900 px-3 py-2 text-sm focus:border-indigo-500 focus:outline-none"
        />
      </div>
      {#if error}
        <p class="text-xs text-red-400">{error}</p>
      {/if}
      <button
        type="submit"
        disabled={loading}
        class="w-full rounded-lg bg-indigo-600 px-4 py-2.5 text-sm font-medium hover:bg-indigo-500 disabled:opacity-50"
      >
        Sign in
      </button>
    </form>

    <p class="text-center text-xs text-neutral-500">
      <a href="/forgot-password" class="text-indigo-400 hover:text-indigo-300">Forgot password?</a>
    </p>
  </div>
</div>

// src/routes/login.tsx
import { createFileRoute, useNavigate, redirect } from '@tanstack/react-router'
import { useState } from 'react'
import {
  signInWithPopup,
  signInWithEmailAndPassword,
  signOut,
  getIdToken,
} from 'firebase/auth'
import { clientAuth, googleProvider } from '~/lib/gip-client'
import { api } from '~/lib/eden'
import { getSessionFn } from '~/server/functions/auth'

export const Route = createFileRoute('/login')({
  validateSearch: (search: Record<string, unknown>) => ({
    redirect: (search.redirect as string) ?? '/',
  }),
  beforeLoad: async () => {
    const user = await getSessionFn()
    if (user) throw redirect({ to: '/' })
  },
  component: LoginPage,
})

function LoginPage() {
  const navigate = useNavigate()
  const { redirect: redirectTo } = Route.useSearch()
  const [email, setEmail] = useState('')
  const [password, setPassword] = useState('')
  const [error, setError] = useState<string | null>(null)
  const [loading, setLoading] = useState(false)

  async function exchangeToken(idToken: string) {
    const { error } = await api.api.auth.session.post({ idToken })
    if (error) throw new Error((error.value as { message?: string })?.message ?? 'Login failed')
    await navigate({ to: redirectTo })
  }

  async function handleGoogle() {
    setError(null)
    setLoading(true)
    try {
      const cred = await signInWithPopup(clientAuth, googleProvider)
      const idToken = await getIdToken(cred.user)
      await exchangeToken(idToken)
    } catch (e) {
      await signOut(clientAuth).catch(() => {})
      setError(e instanceof Error ? e.message : 'Google sign-in failed')
    } finally {
      setLoading(false)
    }
  }

  async function handleEmail(e: React.FormEvent) {
    e.preventDefault()
    setError(null)
    setLoading(true)
    try {
      const cred = await signInWithEmailAndPassword(clientAuth, email, password)
      const idToken = await getIdToken(cred.user)
      await exchangeToken(idToken)
    } catch (e) {
      setError(e instanceof Error ? e.message : 'Sign-in failed')
    } finally {
      setLoading(false)
    }
  }

  return (
    <div className="flex min-h-full items-center justify-center px-4">
      <div className="w-full max-w-sm space-y-8">
        <div className="text-center">
          <h1 className="text-2xl font-semibold tracking-tight">COMS Portal</h1>
          <p className="mt-1 text-sm text-neutral-400">Sign in to continue</p>
        </div>

        <button
          onClick={handleGoogle}
          disabled={loading}
          className="flex w-full items-center justify-center gap-3 rounded-lg border border-neutral-700 bg-neutral-900 px-4 py-2.5 text-sm font-medium hover:bg-neutral-800 disabled:opacity-50"
        >
          <GoogleIcon />
          Continue with Google
        </button>

        <div className="relative">
          <div className="absolute inset-0 flex items-center">
            <div className="w-full border-t border-neutral-800" />
          </div>
          <div className="relative flex justify-center text-xs text-neutral-500">
            <span className="bg-neutral-950 px-2">or</span>
          </div>
        </div>

        <form onSubmit={handleEmail} className="space-y-4">
          <div>
            <label className="mb-1 block text-xs text-neutral-400">Email</label>
            <input
              type="email"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              required
              className="w-full rounded-lg border border-neutral-700 bg-neutral-900 px-3 py-2 text-sm focus:border-indigo-500 focus:outline-none"
            />
          </div>
          <div>
            <label className="mb-1 block text-xs text-neutral-400">Password</label>
            <input
              type="password"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              required
              className="w-full rounded-lg border border-neutral-700 bg-neutral-900 px-3 py-2 text-sm focus:border-indigo-500 focus:outline-none"
            />
          </div>
          {error && <p className="text-xs text-red-400">{error}</p>}
          <button
            type="submit"
            disabled={loading}
            className="w-full rounded-lg bg-indigo-600 px-4 py-2.5 text-sm font-medium hover:bg-indigo-500 disabled:opacity-50"
          >
            {loading ? 'Signing in…' : 'Sign in'}
          </button>
        </form>

        <p className="text-center text-xs text-neutral-500">
          <a href="/forgot-password" className="underline hover:text-neutral-300">
            Forgot password?
          </a>
        </p>
      </div>
    </div>
  )
}

function GoogleIcon() {
  return (
    <svg width="18" height="18" viewBox="0 0 18 18">
      <path fill="#4285F4" d="M17.64 9.2c0-.637-.057-1.251-.164-1.84H9v3.481h4.844c-.209 1.125-.843 2.078-1.796 2.717v2.258h2.908c1.702-1.567 2.684-3.875 2.684-6.615z" />
      <path fill="#34A853" d="M9 18c2.43 0 4.467-.806 5.956-2.18l-2.908-2.259c-.806.54-1.837.86-3.048.86-2.344 0-4.328-1.584-5.036-3.711H.957v2.332A8.997 8.997 0 0 0 9 18z" />
      <path fill="#FBBC05" d="M3.964 10.71A5.41 5.41 0 0 1 3.682 9c0-.593.102-1.17.282-1.71V4.958H.957A8.996 8.996 0 0 0 0 9c0 1.452.348 2.827.957 4.042l3.007-2.332z" />
      <path fill="#EA4335" d="M9 3.58c1.321 0 2.508.454 3.44 1.345l2.582-2.58C13.463.891 11.426 0 9 0A8.997 8.997 0 0 0 .957 4.958L3.964 7.29C4.672 5.163 6.656 3.58 9 3.58z" />
    </svg>
  )
}
