// apps/web/src/routes/(authed)/admin/teams/+page.svelte
<script lang="ts">
  import { teamsQuery } from '$lib/queries/teams'

  const query = teamsQuery()
</script>

<div class="p-8">
  <div class="mb-6 flex items-center justify-between">
    <h1 class="text-xl font-semibold">Teams</h1>
    <a href="/admin/teams/new" class="rounded-lg bg-indigo-600 px-4 py-2 text-sm font-medium hover:bg-indigo-500">New Team</a>
  </div>

  {#if $query.isLoading}
    <div class="animate-pulse space-y-2">
      {#each Array(5) as _}
        <div class="h-12 rounded-lg bg-neutral-800"></div>
      {/each}
    </div>
  {:else if $query.data}
    <table class="w-full text-sm">
      <thead>
        <tr class="border-b border-neutral-800 text-left text-xs text-neutral-400">
          <th class="pb-2 font-medium">Name</th>
          <th class="pb-2 font-medium">Description</th>
          <th class="pb-2 font-medium">Members</th>
          <th class="pb-2 font-medium">Created</th>
        </tr>
      </thead>
      <tbody>
        {#each $query.data as team}
          <tr class="border-b border-neutral-800/50 hover:bg-neutral-900">
            <td class="py-2">
              <a href="/admin/teams/{team.id}" class="text-indigo-400 hover:text-indigo-300">{team.name}</a>
            </td>
            <td class="py-2 text-neutral-400">{team.description ?? '-'}</td>
            <td class="py-2 text-neutral-400">{team.memberCount ?? 0}</td>
            <td class="py-2 text-neutral-400">{new Date(team.createdAt).toLocaleDateString()}</td>
          </tr>
        {/each}
      </tbody>
    </table>
    {#if $query.data.length === 0}
      <p class="mt-4 text-sm text-neutral-500">No teams yet.</p>
    {/if}
  {:else if $query.error}
    <p class="text-sm text-red-400">Failed to load teams.</p>
  {/if}
</div>

// src/routes/_authed/admin/teams.tsx
import { createFileRoute, Link, redirect } from '@tanstack/react-router'
import { useEffect, useState } from 'react'
import { api } from '~/lib/eden'

export const Route = createFileRoute('/_authed/admin/teams')({
  beforeLoad: ({ context }) => {
    const { portalRole } = context.user
    if (portalRole !== 'admin' && portalRole !== 'super_admin') {
      throw redirect({ to: '/' })
    }
  },
  component: TeamsPage,
})

interface Team {
  id: string
  name: string
  description: string | null
  createdAt: string
}

function TeamsPage() {
  const [teams, setTeams] = useState<Team[]>([])
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    api.api.v1.teams.get().then(({ data }) => {
      if (data) setTeams(data as Team[])
      setLoading(false)
    })
  }, [])

  return (
    <div className="p-8">
      <div className="mb-6 flex items-center justify-between">
        <h1 className="text-xl font-semibold">Teams</h1>
        <Link
          to="/admin/teams/new"
          className="rounded-lg bg-indigo-600 px-4 py-2 text-sm font-medium hover:bg-indigo-500"
        >
          New team
        </Link>
      </div>

      {loading ? (
        <div className="space-y-2">
          {Array.from({ length: 3 }).map((_, i) => (
            <div key={i} className="h-14 animate-pulse rounded-xl bg-neutral-800" />
          ))}
        </div>
      ) : teams.length === 0 ? (
        <p className="text-sm text-neutral-500">No teams yet.</p>
      ) : (
        <div className="divide-y divide-neutral-800 rounded-xl border border-neutral-800">
          {teams.map((team) => (
            <Link
              key={team.id}
              to="/admin/teams/$id"
              params={{ id: team.id }}
              className="flex items-center justify-between px-4 py-3 hover:bg-neutral-900"
            >
              <div>
                <p className="text-sm font-medium">{team.name}</p>
                {team.description && (
                  <p className="text-xs text-neutral-400">{team.description}</p>
                )}
              </div>
              <span className="text-xs text-neutral-500">→</span>
            </Link>
          ))}
        </div>
      )}
    </div>
  )
}
