// src/routes/_authed/admin/employees.tsx
import { createFileRoute, Link, redirect } from '@tanstack/react-router'
import { useEffect, useState } from 'react'
import { api } from '~/lib/eden'
import { EmployeeTable } from '~/components/employee-table'

export const Route = createFileRoute('/_authed/admin/employees')({
  beforeLoad: ({ context }) => {
    const { portalRole } = context.user
    if (portalRole !== 'admin' && portalRole !== 'super_admin') {
      throw redirect({ to: '/' })
    }
  },
  component: EmployeesPage,
})

interface Employee {
  id: string
  email: string
  name: string
  department: string | null
  position: string | null
  portalRole: string
  status: string
  createdAt: string
}

function EmployeesPage() {
  const [employees, setEmployees] = useState<Employee[]>([])
  const [total, setTotal] = useState(0)
  const [page, setPage] = useState(1)
  const [search, setSearch] = useState('')
  const [loading, setLoading] = useState(true)

  const limit = 20

  useEffect(() => {
    setLoading(true)
    api.api.v1.employees.get({ query: { page, limit, search: search || undefined } }).then(({ data }) => {
      if (data) {
        setEmployees((data as { employees: Employee[]; total: number }).employees)
        setTotal((data as { employees: Employee[]; total: number }).total)
      }
      setLoading(false)
    })
  }, [page, search])

  return (
    <div className="p-8">
      <div className="mb-6 flex items-center justify-between">
        <h1 className="text-xl font-semibold">Employees</h1>
        <Link
          to="/admin/employees/new"
          className="rounded-lg bg-indigo-600 px-4 py-2 text-sm font-medium hover:bg-indigo-500"
        >
          Add employee
        </Link>
      </div>

      <div className="mb-4">
        <input
          type="search"
          placeholder="Search by name or email…"
          value={search}
          onChange={(e) => { setSearch(e.target.value); setPage(1) }}
          className="w-full max-w-sm rounded-lg border border-neutral-700 bg-neutral-900 px-3 py-2 text-sm focus:border-indigo-500 focus:outline-none"
        />
      </div>

      <EmployeeTable employees={employees} loading={loading} />

      <div className="mt-4 flex items-center justify-between text-sm text-neutral-400">
        <span>{total} employee{total !== 1 ? 's' : ''}</span>
        <div className="flex gap-2">
          <button
            onClick={() => setPage((p) => Math.max(1, p - 1))}
            disabled={page === 1}
            className="rounded px-3 py-1 hover:bg-neutral-800 disabled:opacity-40"
          >
            Previous
          </button>
          <button
            onClick={() => setPage((p) => p + 1)}
            disabled={page * limit >= total}
            className="rounded px-3 py-1 hover:bg-neutral-800 disabled:opacity-40"
          >
            Next
          </button>
        </div>
      </div>
    </div>
  )
}

// apps/web/src/routes/(authed)/admin/employees/+page.svelte
<script lang="ts">
  import { employeesQuery, batchUpdateEmployeesMutation } from '$lib/queries/employees'
  import BatchToolbar from '$lib/components/batch-toolbar.svelte'

  let page = $state(1)
  let search = $state('')
  let selected = $state<Set<string>>(new Set())

  const query = $derived(employeesQuery(page, 20, search))
  const mutation = batchUpdateEmployeesMutation()

  const BATCH_ACTIONS = [
    {
      key: 'portalRole',
      label: 'Change Role',
      options: [
        { value: 'employee', label: 'Employee' },
        { value: 'admin', label: 'Admin' },
        { value: 'super_admin', label: 'Super Admin' },
      ],
    },
  ]

  const allIds = $derived(($query.data?.data ?? []).map((e: any) => e.id))
  const allSelected = $derived(allIds.length > 0 && allIds.every((id: string) => selected.has(id)))

  function toggleAll() {
    if (allSelected) {
      selected = new Set()
    } else {
      selected = new Set(allIds)
    }
  }

  function toggleOne(id: string) {
    const next = new Set(selected)
    if (next.has(id)) next.delete(id)
    else next.add(id)
    selected = next
  }

  async function handleBatchApply(action: string, value: string) {
    await $mutation.mutateAsync({ ids: [...selected], field: action, value })
    selected = new Set()
  }
</script>

<div class="p-8">
  <div class="mb-6 flex items-center justify-between">
    <h1 class="text-xl font-semibold">Employees</h1>
    <a href="/admin/employees/new" class="rounded-lg bg-indigo-600 px-4 py-2 text-sm font-medium hover:bg-indigo-500">Add Employee</a>
  </div>

  <input type="text" placeholder="Search by email..." bind:value={search} class="mb-4 w-full max-w-sm rounded-lg border border-neutral-700 bg-neutral-900 px-3 py-2 text-sm focus:border-indigo-500 focus:outline-none" />

  <div class="mb-3">
    <BatchToolbar
      selectedCount={selected.size}
      actions={BATCH_ACTIONS}
      onApply={handleBatchApply}
      isPending={$mutation.isPending}
      entityLabel="employee"
    />
  </div>

  {#if $query.isLoading}
    <div class="animate-pulse space-y-2">
      {#each Array(5) as _}
        <div class="h-12 rounded-lg bg-neutral-800"></div>
      {/each}
    </div>
  {:else if $query.data}
    <table class="w-full text-sm">
      <thead>
        <tr class="border-b border-neutral-800 text-left text-xs text-neutral-400">
          <th class="pb-2 w-8">
            <input type="checkbox" checked={allSelected} onchange={toggleAll} class="rounded border-neutral-700" />
          </th>
          <th class="pb-2 font-medium">Name</th>
          <th class="pb-2 font-medium">Email</th>
          <th class="pb-2 font-medium">Role</th>
          <th class="pb-2 font-medium">Status</th>
        </tr>
      </thead>
      <tbody>
        {#each $query.data.data as employee}
          <tr class="border-b border-neutral-800/50 hover:bg-neutral-900">
            <td class="py-2">
              <input type="checkbox" checked={selected.has(employee.id)} onchange={() => toggleOne(employee.id)} class="rounded border-neutral-700" />
            </td>
            <td class="py-2"><a href="/admin/employees/{employee.id}" class="text-indigo-400 hover:text-indigo-300">{employee.name}</a></td>
            <td class="py-2 text-neutral-400">{employee.email}</td>
            <td class="py-2"><span class="rounded-full bg-neutral-800 px-2 py-0.5 text-xs">{employee.portalRole}</span></td>
            <td class="py-2"><span class="text-xs" class:text-green-400={employee.status === 'active'} class:text-red-400={employee.status !== 'active'}>{employee.status}</span></td>
          </tr>
        {/each}
      </tbody>
    </table>

    <div class="mt-4 flex items-center justify-between text-xs text-neutral-500">
      <span>{$query.data.total} total</span>
      <div class="flex gap-2">
        <button onclick={() => page = Math.max(1, page - 1)} disabled={page === 1} class="rounded px-2 py-1 hover:bg-neutral-800 disabled:opacity-30">Prev</button>
        <span>Page {page}</span>
        <button onclick={() => page++} disabled={$query.data.data.length < 20} class="rounded px-2 py-1 hover:bg-neutral-800 disabled:opacity-30">Next</button>
      </div>
    </div>
  {/if}
</div>
